<?php
/**
 * AccessBadgesApi
 * PHP version 7.2
 *
 * @category Class
 * @package  OptimaBridge
 * @author   Quentin GUERIN (quentin.guerin@neoweb.fr)
 * @link     https://openapi-generator.tech
 */

/**
 * Optima-Bridge API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: quentin.guerin@neoweb.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OptimaBridge\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use OptimaBridge\ApiException;
use OptimaBridge\Configuration;
use OptimaBridge\HeaderSelector;
use OptimaBridge\ObjectSerializer;

/**
 * AccessBadgesApi Class Doc Comment
 *
 * @category Class
 * @package  OptimaBridge
 * @author   Quentin GUERIN (quentin.guerin@neoweb.fr)
 * @link     https://openapi-generator.tech
 */
class AccessBadgesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation deleteAccessBadges
     *
     * Disallow some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be disallowed on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OptimaBridge\Model\Process
     */
    public function deleteAccessBadges($access_badge)
    {
        list($response) = $this->deleteAccessBadgesWithHttpInfo($access_badge);
        return $response;
    }

    /**
     * Operation deleteAccessBadgesWithHttpInfo
     *
     * Disallow some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be disallowed on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OptimaBridge\Model\Process, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteAccessBadgesWithHttpInfo($access_badge)
    {
        $request = $this->deleteAccessBadgesRequest($access_badge);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 202:
                    if ('\OptimaBridge\Model\Process' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OptimaBridge\Model\Process', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OptimaBridge\Model\Process';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OptimaBridge\Model\Process',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation deleteAccessBadgesAsync
     *
     * Disallow some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be disallowed on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAccessBadgesAsync($access_badge)
    {
        return $this->deleteAccessBadgesAsyncWithHttpInfo($access_badge)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation deleteAccessBadgesAsyncWithHttpInfo
     *
     * Disallow some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be disallowed on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAccessBadgesAsyncWithHttpInfo($access_badge)
    {
        $returnType = '\OptimaBridge\Model\Process';
        $request = $this->deleteAccessBadgesRequest($access_badge);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'deleteAccessBadges'
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be disallowed on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteAccessBadgesRequest($access_badge)
    {
        // verify the required parameter 'access_badge' is set
        if ($access_badge === null || (is_array($access_badge) && count($access_badge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_badge when calling deleteAccessBadges'
            );
        }

        $resourcePath = '/access_badges/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($access_badge)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($access_badge));
            } else {
                $httpBody = $access_badge;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation patchAccessBadges
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OptimaBridge\Model\Process
     */
    public function patchAccessBadges($access_badge)
    {
        list($response) = $this->patchAccessBadgesWithHttpInfo($access_badge);
        return $response;
    }

    /**
     * Operation patchAccessBadgesWithHttpInfo
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OptimaBridge\Model\Process, HTTP status code, HTTP response headers (array of strings)
     */
    public function patchAccessBadgesWithHttpInfo($access_badge)
    {
        $request = $this->patchAccessBadgesRequest($access_badge);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 202:
                    if ('\OptimaBridge\Model\Process' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OptimaBridge\Model\Process', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OptimaBridge\Model\Process';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OptimaBridge\Model\Process',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation patchAccessBadgesAsync
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchAccessBadgesAsync($access_badge)
    {
        return $this->patchAccessBadgesAsyncWithHttpInfo($access_badge)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation patchAccessBadgesAsyncWithHttpInfo
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function patchAccessBadgesAsyncWithHttpInfo($access_badge)
    {
        $returnType = '\OptimaBridge\Model\Process';
        $request = $this->patchAccessBadgesRequest($access_badge);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'patchAccessBadges'
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function patchAccessBadgesRequest($access_badge)
    {
        // verify the required parameter 'access_badge' is set
        if ($access_badge === null || (is_array($access_badge) && count($access_badge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_badge when calling patchAccessBadges'
            );
        }

        $resourcePath = '/access_badges/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($access_badge)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($access_badge));
            } else {
                $httpBody = $access_badge;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PATCH',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation postAccessBadges
     *
     * Allow some new access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that need to be allowed on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OptimaBridge\Model\Process
     */
    public function postAccessBadges($access_badge)
    {
        list($response) = $this->postAccessBadgesWithHttpInfo($access_badge);
        return $response;
    }

    /**
     * Operation postAccessBadgesWithHttpInfo
     *
     * Allow some new access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that need to be allowed on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OptimaBridge\Model\Process, HTTP status code, HTTP response headers (array of strings)
     */
    public function postAccessBadgesWithHttpInfo($access_badge)
    {
        $request = $this->postAccessBadgesRequest($access_badge);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 202:
                    if ('\OptimaBridge\Model\Process' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OptimaBridge\Model\Process', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OptimaBridge\Model\Process';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OptimaBridge\Model\Process',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation postAccessBadgesAsync
     *
     * Allow some new access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that need to be allowed on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postAccessBadgesAsync($access_badge)
    {
        return $this->postAccessBadgesAsyncWithHttpInfo($access_badge)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation postAccessBadgesAsyncWithHttpInfo
     *
     * Allow some new access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that need to be allowed on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function postAccessBadgesAsyncWithHttpInfo($access_badge)
    {
        $returnType = '\OptimaBridge\Model\Process';
        $request = $this->postAccessBadgesRequest($access_badge);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'postAccessBadges'
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that need to be allowed on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function postAccessBadgesRequest($access_badge)
    {
        // verify the required parameter 'access_badge' is set
        if ($access_badge === null || (is_array($access_badge) && count($access_badge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_badge when calling postAccessBadges'
            );
        }

        $resourcePath = '/access_badges/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($access_badge)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($access_badge));
            } else {
                $httpBody = $access_badge;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation putAccessBadges
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \OptimaBridge\Model\Process
     */
    public function putAccessBadges($access_badge)
    {
        list($response) = $this->putAccessBadgesWithHttpInfo($access_badge);
        return $response;
    }

    /**
     * Operation putAccessBadgesWithHttpInfo
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \OptimaBridge\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \OptimaBridge\Model\Process, HTTP status code, HTTP response headers (array of strings)
     */
    public function putAccessBadgesWithHttpInfo($access_badge)
    {
        $request = $this->putAccessBadgesRequest($access_badge);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 202:
                    if ('\OptimaBridge\Model\Process' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\OptimaBridge\Model\Process', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\OptimaBridge\Model\Process';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 202:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\OptimaBridge\Model\Process',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation putAccessBadgesAsync
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putAccessBadgesAsync($access_badge)
    {
        return $this->putAccessBadgesAsyncWithHttpInfo($access_badge)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation putAccessBadgesAsyncWithHttpInfo
     *
     * Update some allowed access badges on Optima-Box
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function putAccessBadgesAsyncWithHttpInfo($access_badge)
    {
        $returnType = '\OptimaBridge\Model\Process';
        $request = $this->putAccessBadgesRequest($access_badge);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'putAccessBadges'
     *
     * @param  \OptimaBridge\Model\AccessBadge[] $access_badge Access badge objects that must be updated on Optima-Box (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function putAccessBadgesRequest($access_badge)
    {
        // verify the required parameter 'access_badge' is set
        if ($access_badge === null || (is_array($access_badge) && count($access_badge) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $access_badge when calling putAccessBadges'
            );
        }

        $resourcePath = '/access_badges/';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($access_badge)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($access_badge));
            } else {
                $httpBody = $access_badge;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }


        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
