<?php
/**
 * PersonTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  OptimaBridge\Client
 * @author   Quentin GUERIN (quentin.guerin@neoweb.fr)
 * @link     https://openapi-generator.tech
 */

/**
 * Optima-Bridge API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: quentin.guerin@neoweb.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OptimaBridge\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PersonTest Class Doc Comment
 *
 * @category    Class
 * @description Person
 * @package     OptimaBridge\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PersonTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "Person"
     */
    public function testPerson()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "firstname"
     */
    public function testPropertyFirstname()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
