<?php
/**
 * AccessBadgesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Optima-Bridge API Specification
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * Contact: quentin.guerin@neoweb.fr
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.26
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;

/**
 * AccessBadgesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class AccessBadgesApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for deleteAccessBadges
     *
     * Disallow some allowed access badges on Optima-Box.
     *
     */
    public function testDeleteAccessBadges()
    {
    }

    /**
     * Test case for patchAccessBadges
     *
     * Update some allowed access badges on Optima-Box.
     *
     */
    public function testPatchAccessBadges()
    {
    }

    /**
     * Test case for postAccessBadges
     *
     * Allow some new access badges on Optima-Box.
     *
     */
    public function testPostAccessBadges()
    {
    }

    /**
     * Test case for putAccessBadges
     *
     * Update some allowed access badges on Optima-Box.
     *
     */
    public function testPutAccessBadges()
    {
    }
}
