<?php
/**
 * AccessBadgesApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  OptimaBridge
 * @author   Quentin GUERIN (quentin.guerin@neoweb.fr)
 * @link     https://openapi-generator.tech
 */

/**
 * Optima-Bridge API Specification
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: quentin.guerin@neoweb.fr
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OptimaBridge\Test\Api;

use \OptimaBridge\Configuration;
use \OptimaBridge\ApiException;
use \OptimaBridge\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AccessBadgesApiTest Class Doc Comment
 *
 * @category Class
 * @package  OptimaBridge
 * @author   Quentin GUERIN (quentin.guerin@neoweb.fr)
 * @link     https://openapi-generator.tech
 */
class AccessBadgesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteAccessBadges
     *
     * Disallow some allowed access badges on Optima-Box.
     *
     */
    public function testDeleteAccessBadges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for patchAccessBadges
     *
     * Update some allowed access badges on Optima-Box.
     *
     */
    public function testPatchAccessBadges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postAccessBadges
     *
     * Allow some new access badges on Optima-Box.
     *
     */
    public function testPostAccessBadges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putAccessBadges
     *
     * Update some allowed access badges on Optima-Box.
     *
     */
    public function testPutAccessBadges()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
